{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "spark-application-event-watcher.serviceAccountName" . | trim}}"
  labels:
    app.kubernetes.io/name: "{{ include "spark-application-event-watcher.name" . | trim}}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "spark-application-event-watcher.name" . | trim}}-role"
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "spark-application-event-watcher.name" . | trim}}-rolebinding"
subjects:
  - kind: ServiceAccount
    name: "{{ include "spark-application-event-watcher.serviceAccountName" . | trim}}"
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: "{{ include "spark-application-event-watcher.name" . | trim}}-role"
  apiGroup: rbac.authorization.k8s.io
{{- end }}