apiVersion: v1
kind: Service
metadata:
  name: spark-application-event-watcher
spec:
  selector:
    app: spark-application-event-watcher
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: {{ .Values.service.type }}
