image:
  repository: spark-application-event-watcher
  tag: 1.0-SNAPSHOT
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

rbac:
  create: true

serviceAccount:
  create: true
  name: spark-application-event-watcher